### ISSUE TITLE
Adding _score raises Fielddata error

### ISSUE THREAD

**Issue by bryancaragay** [barseghyanartur/django-elasticsearch-dsl-drf#163]
I've read the docs a few times, and read all the answers pertaining to this area on this repo, but I am curious if I have just misconfigured something.

I am running all the latest versions (Python, ES, this repo), and I have basic searching working. However, when I go to modify the `ordering` field to sort by `_score` first, I start getting this error:

`RequestError(400, 'search_phase_execution_exception', 'Fielddata is disabled on text fields by default. Set fielddata=true on [name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.')`

This error only arises when I modify the code to contain the `_score` ordering. Any other ordering using my model fields works as expected.

Wondering if I possibly misconfigured something, and hoping the answer is here somewhere.

**Comment by barseghyanartur** [comment]
@bryancaragay:

It's must be a configuration issue. Please, check example project (run locally) and see if you have similar issue (likely not). If it is, please, mention it here along with full stack-trace.

Some links for you:

- [ordering_by_score_compound_search](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/viewsets/book/ordering_by_score_compound_search.py): Check corresponding viewset, experiment with ordering, see if you run it locally with no issues. 
- See the FAQ section on [sorting by relevance](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/faq.html#questions-and-answers).

Also, search all other open and closed issues for similar answers.

If you find out what the problem is, please, consider updating the FAQ (in docs) and make pull request.
