### ISSUE TITLE
Implement highlighting

### ISSUE THREAD

**Issue by id13** [barseghyanartur/django-elasticsearch-dsl-drf#18]
Hi,

It would be nice to have a way to pass highlight options, maybe as a new `highlight_fields` in viewsets (used by `SearchFilterBackend`) or just add an attribute pass all sorts of cusom kwargs to django dsl's queries (including but not limited to `highlights`).

No matter how you decide it should be done, the second part of the problem is to figure out a way to pass the highlights to serializers. Any idea ?

I am willing to implement it.

**Comment by barseghyanartur** [comment]
@id13:

``highlight_fields`` seems reasonable. I think it makes sense to implement it in a similar way to facets (by default disabled, unless explicitly enabled; in order to activate, a query param highlight=fieldname shall be given). It won't be used it in other backends, right?

**Comment by id13** [comment]
@barseghyanartur 
To the best of my knowledge, it can be used whenever a match query is used, but it does not really makes sense to have it in other backends.
Your spec sounds good to me, I am on my way to implement it.

**Comment by barseghyanartur** [comment]
@id13:

The ``match`` query is also used in filtering backends.

- http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#highlighting

I think it might make sense to implement it as a separate independent backend, so that it could be used with other backends as well.

However, it's also fine if you implement it for search backend only. It can always be refactored later on (as long as API stays the same).
