### ISSUE TITLE
Add options when using CompoundSearchFilterBackend?

### ISSUE THREAD

**Issue by adl-asi** [barseghyanartur/django-elasticsearch-dsl-drf#199]
**Questions**

I want to add the 'fuzziness': 'AUTO' option, when using Compound Search backend. Is this possible? What is the name of the options parameter when using Compound Search.

Example, this is how I would do it if using Multi Match

`multi_match_options = {
        'fuzziness': 'AUTO'
    }`

**Comment by barseghyanartur** [comment]
@adl-asi:

Yes. You could make your own `FuzzyMatchQueryBackend` like shown [here](https://github.com/waam-app/django-elasticsearch-dsl-drf/commit/d0201871fc787ec55e4147b16cd54fc6730c6165) and then make another `CompoundFuzzySearchFilterBackend` by simply pointing at yours.

However, since it's not the first time this is being asked for, I'm adding it to the TODOs and plan to work on this in the nearest future. In the meanwhile, you could do as I proposed above.

**Comment by barseghyanartur** [comment]
Actually, it works with all compound search filter backends as shown [here](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/viewsets/book/compound_search.py#L53):

```python
class BookCompoundFuzzySearchBackendDocumentViewSet(DocumentViewSet):
   # ...
    filter_backends = [
        CompoundSearchFilterBackend,
    ]

    search_fields = {
        'title': {'fuzziness': 'AUTO'},
        'description': None,
        'summary': None,
    }
```

Search would result into the following query:

```
{
  "from": 0,
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "title": {
              "fuzziness": "AUTO",
              "query": "Performance"
            }
          }
        },
        {
          "match": {
            "description": {
              "query": "Performance"
            }
          }
        },
        {
          "match": {
            "summary": {
              "query": "Performance"
            }
          }
        }
      ]
    }
  },
  "size": 1
}
```
