### ISSUE TITLE
A new project that does pip install django-elasticsearch-dsl-drf will have incompatible versions of django-elasticsearch-dsl and elasticsearch-dsl

### ISSUE THREAD

**Issue by Alexgmin** [barseghyanartur/django-elasticsearch-dsl-drf#27]
` pip install django-elasticsearch-dsl-drf` will install django-elasticsearch-dsl-0.4.4 and elasticsearch-dsl-6.1.0 which are incompatible. 
For example the String class doesn't exist anymore in elasticsearch 6.

**Comment by barseghyanartur** [comment]
@Alexgmin:

I'll explain why.

There are multiple versions of Python bindings for Elasticsearch on PyPI.

For Elasticsearch 2.x you should be using:

- ``elasticsearch`` 2.x
- ``elasticsearch-dsl`` 2.x 

For Elasticsearch 5.x you should be using:

- ``elasticsearch`` 5.x
- ``elasticsearch-dsl`` 5.x 

Same goes for Elasticsearch 6.x.

Since eventually, this library, aims to support multiple versions of Elasticsearch, setup.py does **not** specify certain version of ``elasticsearch`` or ``elasticsearch-dsl``. 

Developers are supposed to install relevant versions of the above mentioned libraries prior installing this library.

I'm closing this ticket for now. Do not hesitate to ask questions though.

**Comment by Alexgmin** [comment]
I agree that the developers are supposed to check the versions installed, however since this package has elasticsearch and elasticsearch-dsl as dependencies, these dependencies should have minimum and maximum versions. 

For example the 5.x branch of elasticsearch-dsl indicates on its setup.py that doesn't support Elasticsearch 6. Just like the master branch of django-elasticsearch-dsl. https://github.com/sabricot/django-elasticsearch-dsl/blob/v0.4.0/setup.py

**Comment by barseghyanartur** [comment]
@Alexgmin:

I disagree, because I'm pretty sure this package will work fine (with no modifications) with Elasticsearch 6.x as soon as ``django-elasticsearch-dsl`` would support it.

Officially supported versions of the Elasticsearch are mentioned in the docs. Installation of the relevant bindings is trivial.
