### ISSUE TITLE
Implement geo-spatial search/filtering/ordering filter backend

### ISSUE THREAD

**Issue by barseghyanartur** [barseghyanartur/django-elasticsearch-dsl-drf#4]
Implement geo-spatial search/filtering/ordering filter backend.

**Comment by id13** [comment]
I am interested in other features of GeoSpace, I can either implement those the same way I did for `geo_distance`, and leave the backend implementation to you. 
Or if you already have  a spec in mind for the backend, I can code it.

**Comment by barseghyanartur** [comment]
@id13:

Excellent! I'm heavily using this library myself, although not yet for geo-spatial purposes, but I'm planning to in nearest future.

I think what would work best it if I first separate the geo-spatial features into a separate backend so that you can work in there. In that way, we can move the tests too.

I'll let you know when I'm done.

**Comment by barseghyanartur** [comment]
Taken from docs. This is what I think needs to be supported.

Elasticsearch supports two types of geo data:

- geo_point fields which support lat/lon pairs
- geo_shape fields, which support points, lines, circles, polygons,
  multi-polygons etc.

The queries in this group are:

- geo_shape query: Find document with geo-shapes which either intersect,
  are contained by, or do not intersect with the specified geo-shape.
- geo_bounding_box query: Finds documents with geo-points that fall into
  the specified rectangle.
- geo_distance query: Finds document with geo-points within the specified
  distance of a central point.
- geo_distance_range query: Like the geo_distance query, but the range
  starts at a specified distance from the central point.
- geo_polygon query: Find documents with geo-points within the specified
  polygon.

This is for filtering. Ordering shall be supported too (where applicable).

**Comment by barseghyanartur** [comment]
@id13:

I started to work on the set of [geo-distance range filters](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/constants.py#L189).

**Comment by id13** [comment]
@barseghyanartur: 
Ok, Il will start on geo_distance ordering.

Concerning geo-distance range filters, are you aware that the [example](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/constants.py#L230) you gave in the doc is [deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-range-query.html) ? 

This should be replaced with [aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geodistance-aggregation.html) [(source)](https://discuss.elastic.co/t/how-to-query-or-filter-by-geo-distance-range-in-elastic-5-x/76758).

Since the distance (from, to) parameters seem to be integer (to be confirmed) I believe lte, gte, lt, gt are simple enough to implement (see the examples)

**Comment by barseghyanartur** [comment]
@id13:

- Regarding geo-distance ordering - great!
- Regarding the deprecation of the geo-distance range filters - what a waste of time. Honestly, I din't notice that, but - yes, if it's going to be deprecated, it does not make sense to make it now. Thanks for bringing it up.

**Comment by barseghyanartur** [comment]
@id13:

The geo-spatial filtering backends with support of geo-distance and geo-polygon have made it into the [0.4](https://pypi.python.org/pypi/django-elasticsearch-dsl-drf/0.4).
