### ISSUE TITLE
How to use "_source" in search URL?

### ISSUE THREAD

**Issue by JasonHXiang** [barseghyanartur/django-elasticsearch-dsl-drf#58]
hi~ I used "_source" in elasticsearch to show some certain fields in the searching results like this.

GET /_search
{
    "query":   { "match_all": {}},
    "_source": [ "title", "created" ]
}

so, I wonder how to use "_source" with django-elasticsearch-dsl-drf，need someone help~

BTW, I've tried http://localhost:8080/search/books/?_source=author, but the results return with all fields defined in serializers.

**Comment by barseghyanartur** [comment]
@JasonHXiang:

The ``_source`` usage is not supported at the moment. However, technically it can be easily implemented. 

It's a bit tricky, though. On one hand, I understand that for instance, in case of really indexes with lots of fields, it might be wise to use ``_source`` for performance optimisation, but in that case, serializer shall take control over it. Since, obviously, if we have listed fields in serializer, we want them to be displayed.

What's your vision about it? What's your use-case?
