### ISSUE TITLE
Question regarding search for name aliases.

### ISSUE THREAD

**Issue by matali1** [barseghyanartur/django-elasticsearch-dsl-drf#74]
Hi,

I am building an index that would allow to search for gene names (search as you type).
User could search by gene’s name, symbol, entrez number (id) or aliases. Not all genes have aliases and they might be short and long (no rules really).

Example gene
```
{
                        "symbol": "KPNB1",
                        "entrez": "3837",
                        "name": "karyopherin (importin) beta 1",
                        "aliases": "IPOB MGC2155 MGC2156 Impnb NTF97 IMB1 MGC2157 IPO1"
},
```
I use Completion Suggester to search by symbol and entrez and use Functional Suggester to search by its name but not sure what's the best way to handle aliases.
I also thought about Functional Suggester but the way I indexed it right now (one field with many aliases) it produces too many results.

Any ideas how to better handle it? Looks like would I need a Completion Suggester for each separate alias but then I don't know how the document should look like.

Any ideas?
Thanks

**Comment by barseghyanartur** [comment]
@matali1:

Question: That record that you showed, does that belong to a single genre record? My first thought would be, if you want to make it searchable, why don't you make a single field that would combine all the data, use `edge_ngram_completion` to index it and search on that whole field instead of joining results with multiple records.

Elastic has a very straight forward way of dealing with aliases. It's called synonyms. They are very easy to use and you can specify then on per-field basis. I would certainly do that.

Additionally, it helps to specify language of your data to get better results. Elastic supports huge amount of languages.

**Comment by matali1** [comment]
Thanks @barseghyanartur 
I am using Django and your package `django-elasticsearch-dsl-drf` and `django-elasticsearch-dsl` so I have `GeneDocument` that deals with it and I follow your examples (`GeneDocumentViewset`) how to query, etc.

Good point that I can use `edge_ngram_completion` for more fields, so I don't need to make several queries however I somehow not sure about aliases.

These aliases have different lengths, some are short so if I do 3grams then I am afraid I can hit many cases of finding string in the middle of the names. If I do longer (4+grams), then I can miss short names...

Regarding synonyms - could you point to the doc?

**Comment by barseghyanartur** [comment]
@matali1:

If you're worried about too many results (I'm not sure what kind of data are you dealing with), you could use `prefix`; you assume that word has been typed correctly. In that case, you don't use ngrams.

Regarding docs - just search "elasticsearch synonyms".
This is just [one of them](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html).
