### ISSUE TITLE
Sync partial data of all objects with --populate?

### ISSUE THREAD

**Issue by JasonHXiang** [barseghyanartur/django-elasticsearch-dsl-drf#87]
Hi, @barseghyanartur.
When I use 
`manage.py search_index --models app.book --populate`
, it will index all the objects of this model. output is like this:
`Indexing 2078 'Book' objects`

but with the count of objects growing, the populate operation will cost too much time.
I wonder how I can just sync the partial data of all objects. For example, I just want to sync the data of the latest-created objects to the elasticsearch.

Wait for your reply!

Sincerely.

**Comment by barseghyanartur** [comment]
@JasonHXiang:

Good question. Since it's not the first time that you're raising a question about a well documented issue, I need to ask you to take time for studying documentation before raising an issue here.

As for the answer of your question, [read this](https://django-elasticsearch-dsl-drf.readthedocs.io/en/0.16.3/quick_start.html#sample-partial-sync-using-custom-signals).
