### ISSUE TITLE
Question about how to filter suggestions

### ISSUE THREAD

**Issue by turukawa** [barseghyanartur/django-elasticsearch-dsl-drf#94]
Hi, have hunted through the help on this but I'm quite far out of my depth.

I have an autocomplete address search I want to filter by region (there are an awful lot of High Streets in the UK). I'm migrating an existing Django Haystack implementation to django-elasticsearch-dsl-drf.

I understand from the docs I need to add "suggest" to the object document. And then something about a context which I see in the [ElasticSearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/suggester-context.html), but I don't know how to implement that here, or how I would call that in the url parameters? The docs may tell me, but it's a little unclear.

Any help would be much appreciated, thanks.

Gavin

**Comment by barseghyanartur** [comment]
@turukawa:

Good question. I haven't touched that part (yet). There are two questions here for you.

1. How to defined that on the document level (you should find that out in `elasticsearch-dsl`) .
2. How to use it in filtering using this package.

As of 2 - it's not yet implemented. So, you could either (a) implement it yourself (in that case, I encourage you to submit a pull request upon success) or (b) ask me to do that (contact me for conditions; I could assist you in doing 1) or (c) this issue is left open until I (or someone else) have time for it.

**Comment by turukawa** [comment]
@barseghyanartur 

As mentioned, I'm far out of my depth on this and not sure I'd be of much technical use. I've read the elasticsearch docs, but not sure how to implement that unless I'm somehow needing to bypass the DRF approach in this package?

My open data project was supposed to be live today, and then I discovered Django Haystack doesn't support elasticsearch 6, and <6 won't run on Ubuntu 18, and it took two weeks for the database to build ... so, happy to discuss you implementing this, just let me know how to contact you.

**Comment by barseghyanartur** [comment]
@turukawa:

Implemented in 0.17. Documentation is updated (but needs some improvements).

https://django-elasticsearch-dsl-drf.readthedocs.io/en/0.17/advanced_usage_examples.html#context-suggesters
